// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;

namespace BookStore.Core.Entities.Models;

public partial class Bookitem
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Author { get; set; }

    public string Content { get; set; }

    public int? StatusId { get; set; }

    public string ImageUrl { get; set; }

    public DateTime? CreationDate { get; set; }

    public DateTime? PublishedDate { get; set; }
    public virtual Status Status { get; set; }
}