USE [master]
GO
/****** Object:  Database [nonstopio]    Script Date: 19-08-2023 19:31:07 ******/
CREATE DATABASE [nonstopio]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'nonstopio', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\nonstopio.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'nonstopio_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\nonstopio_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [nonstopio] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [nonstopio].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [nonstopio] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [nonstopio] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [nonstopio] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [nonstopio] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [nonstopio] SET ARITHABORT OFF 
GO
ALTER DATABASE [nonstopio] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [nonstopio] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [nonstopio] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [nonstopio] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [nonstopio] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [nonstopio] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [nonstopio] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [nonstopio] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [nonstopio] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [nonstopio] SET  ENABLE_BROKER 
GO
ALTER DATABASE [nonstopio] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [nonstopio] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [nonstopio] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [nonstopio] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [nonstopio] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [nonstopio] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [nonstopio] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [nonstopio] SET RECOVERY FULL 
GO
ALTER DATABASE [nonstopio] SET  MULTI_USER 
GO
ALTER DATABASE [nonstopio] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [nonstopio] SET DB_CHAINING OFF 
GO
ALTER DATABASE [nonstopio] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [nonstopio] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [nonstopio] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [nonstopio] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'nonstopio', N'ON'
GO
ALTER DATABASE [nonstopio] SET QUERY_STORE = ON
GO
ALTER DATABASE [nonstopio] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [nonstopio]
GO
/****** Object:  Table [dbo].[bookitem]    Script Date: 19-08-2023 19:31:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[bookitem](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](max) NULL,
	[Author] [nvarchar](20) NULL,
	[Content] [nvarchar](max) NULL,
	[StatusId] [int] NULL,
	[ImageUrl] [nvarchar](max) NULL,
	[Creation_Date] [datetime2](7) NULL,
	[Published_Date] [datetime2](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Status]    Script Date: 19-08-2023 19:31:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Status](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 19-08-2023 19:31:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NULL,
	[Email] [nvarchar](max) NULL,
	[Password] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[bookitem]  WITH CHECK ADD FOREIGN KEY([StatusId])
REFERENCES [dbo].[Status] ([Id])
GO
USE [master]
GO
ALTER DATABASE [nonstopio] SET  READ_WRITE 
GO
