// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using BookStore.Core.Entities.Models;
using Microsoft.EntityFrameworkCore;

namespace BookStore.Core.Entities;

public partial class nonstopioContext : DbContext
{
    public nonstopioContext(DbContextOptions<nonstopioContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Bookitem> Bookitems { get; set; }

    public virtual DbSet<Status> Statuses { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Bookitem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__bookitem__3214EC07FA3C1E02");

            entity.ToTable("bookitem");

            entity.Property(e => e.Author).HasMaxLength(20);
            entity.Property(e => e.CreationDate).HasColumnName("Creation_Date");
            entity.Property(e => e.PublishedDate).HasColumnName("Published_Date");

            entity.HasOne(d => d.Status).WithMany(p => p.Bookitems)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__bookitem__Status__398D8EEE");
        });

        modelBuilder.Entity<Status>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Status__3214EC07A73A1A48");

            entity.ToTable("Status");

            entity.Property(e => e.Name)
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Users__3214EC0767E3649F");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}